[sims]
base_dir = "/hpcdata0/simulations/BAHAMAS/"
sim_dirs = [
     # "AGN_TUNED_nu0_L100N256_WMAP9",
     # "DMONLY_2fluid_nu0_L100N256_WMAP9",
     "AGN_TUNED_nu0_L400N1024_WMAP9",
     # "AGN_TUNED_nu0_L400N1024_Planck"
]
sim_type = "BAHAMAS"
# scalar or list of lists for each sim_dir
#
snapshots = 32
box_sizes = 400
ptypes = [0, 1, 4, 5]

  # # only provide this if no coords files saved manually
  # [sims.coords]
  # # overrides maps.coords_name if provided
  # coords_dir = "/hpcdata0/simulations/BAHAMAS/extsdeba/coords/"
  # coords_name = "clusters_m200m"
  # coord_dset = "FOF/GroupCentreOfPotential"
  # # masses are read in in M_sun / h
  # group_dset = "FOF/Group_M_Mean200"
  # group_range = [1e14, 1e16]
  # extra_dsets = ["FOF/Group_M_Crit500", "FOF/Group_M_Crit200"]

[slices]
# size in units of box size of box slices
slice_size = 1
# axis along which slice is performed
slice_axes = [0]
# parent directory to save slice files in
save_dir = "/hpcdata0/simulations/BAHAMAS/extsdeba/slices/"
# all files will be saved under
# {save_dir}/{sim_dir}/axis_{slice_axis}_size_{slice_size}_{snapshot:03d}_{i:d}.hdf5

[maps]
save_dir = "/hpcdata0/simulations/BAHAMAS/extsdeba/maps/"
map_types = ["gas_mass", "dm_mass", "stars_mass", "bh_mass", "sz"]
# maps are saved as
# {save_dir}/{sim_dir}/{slice_axis}_map_{map_type}_{coords_name}.hdf5

# details of the map, all in units of box size
map_size = 5
map_thickness = 10
map_res = 0.05
# coords files are expected in
# {coords_dir}/{sim_dir}/{coords_name}.hdf5
coords_dir = "/hpcdata0/simulations/BAHAMAS/extsdeba/coords/"
coords_name = "clusters_m200m"

[observables]
# which maps should be saved
observable_types = ""
save_dir = "/hpcdata0/simulations/BAHAMAS/extsdeba/observables/"

# [DIRECTORIES]
# FIGURE_DIR = /Users/stijn/Documents/PhD/projects/aperture_masses/figures/
# DATA_DIR = /Users/stijn/Documents/PhD/projects/aperture_masses/data/
